### ISSUE TITLE
Create new live demo site

### ISSUE THREAD

**Issue by scytherswings** [scytherswings/Network-Status-Page#13]
It looks like the original project has been taken down. I'll see if I can put up a new demo website if I can do it for free....

**Comment by duramato** [comment]
@scytherswings I have a small media server at home that could run it (it is up almost 24/7 but not guaranteed multiple factors power might be down,the internet,etc ), not sure if you are interested as its not the same as dedicated hosting..

**Comment by scytherswings** [comment]
@duramato I might take you up on that, but I'll let you know once I finalize some ideas
