### ISSUE TITLE
is this still under development?

### ISSUE THREAD

**Issue by seanvree** [scytherswings/Network-Status-Page#19]
I see a few forks out there, but none seem to be active.  This is a great project! Just wondering if there is another project out there that is active.

**Comment by scytherswings** [comment]
Sorry, this is not being maintained anymore. Feel free to fork it if you like!

**Comment by seanvree** [comment]
@scytherswings  - Cool. You know of an active alternative?

**Comment by scytherswings** [comment]
Unfortunately no. https://github.com/scytherswings/Plex-Board is supposed to be an alternative but I have gotten sidetracked onto different projects. I intend to update that project once things settle down with my job and extracurriculars, and if people show interest in it again I'm more likely to come back to it ;)

**Comment by seanvree** [comment]
@scytherswings  - It's awesome! I can't get plex-board to run on windows.  But I can't seem to find a good replacement that shows the status of all my plex-related services on one page.  

however, I almost have yours running on windows, but I can't get past these erorrs:

Notice: Undefined index: wan2_ip in C:\inetpub\wwwroot\Network-Status-Page\assets\php\Functions.php on line 25

Notice: Undefined index: storage in C:\inetpub\wwwroot\Network-Status-Page\assets\php\Functions.php on line 48

Notice: Undefined index: storage in C:\inetpub\wwwroot\Network-Status-Page\assets\php\Functions.php on line 49

Fatal error: Call to undefined function sys_getloadavg() in C:\inetpub\wwwroot\Network-Status-Page\assets\php\Functions.php on line 308

Notice: Undefined index: wan2_ip in C:\inetpub\wwwroot\Network-Status-Page\assets\php\Functions.php on line 25

Notice: Undefined index: storage in C:\inetpub\wwwroot\Network-Status-Page\assets\php\Functions.php on line 48

Notice: Undefined index: storage in C:\inetpub\wwwroot\Network-Status-Page\assets\php\Functions.php on line 49

Fatal error: Call to undefined function sys_getloadavg() in C:\inetpub\wwwroot\Network-Status-Page\assets\php\Functions.php on line 308


Anyway, i'd love to see one of these projects get back up! was talking with @d4rk22 and he seems interested too. I'm a windows/python guru, so with some help I can could get it working on windows.

**Comment by scytherswings** [comment]
It looks like you might be missing those keys in your `config.ini` file. Did you delete them? That modification was made back when I was really new to this stuff and it wasn't done all that well. You can go through `functions.php` and comment out those lines and see what happens.


I'm looking at `functions.php` now and it's more nasty than I remembered. Ugh I should work on Plex-Board, it's a lot easier to manage entities, though it does have less features currently...

**Comment by seanvree** [comment]
@scytherswings honestly - I would stick with this version.  I think most poeple just want a one-pager. Plus, I think it's a lot easier to manage as far as the code.  One config file.  That's just me.  

Yeah, I got the error fixed,   

Looks like all the now playing stuff needs to be udpated with the plex updates:

Warning: simplexml_load_file(): http://seanvree.com:32400/web/index.html#!/status/playing:35: parser error : Opening and ending tag mismatch: link line 34 and head in C:\inetpub\wwwroot\Network-Status-Page\assets\php\now_playing_title_ajax.php on line 23

Warning: simplexml_load_file(): </head> in C:\inetpub\wwwroot\Network-Status-Page\assets\php\now_playing_title_ajax.php on line 23
