### ISSUE TITLE
Weather forecast

### ISSUE THREAD

**Issue by duramato** [scytherswings/Network-Status-Page#3]
Is it possible to make the temperature appear in Celcius instead of Fahrenheit?

**Comment by scytherswings** [comment]
I believe I can add an entry in the config file that will convert the Fahrenheit temperature to Celsius. This will be an added feature for the future.

**Comment by scytherswings** [comment]
@duramato I have added this option into the config file under "weather_unit." Let me know what you think.

**Comment by duramato** [comment]
Thanks,works like a charm :)
