### ISSUE TITLE
Question: Storage

### ISSUE THREAD

**Issue by duramato** [scytherswings/Network-Status-Page#6]
Small question,how do i add multiple storage devices?

**Comment by scytherswings** [comment]
Right now, the only way to show storage devices is through the use of the "storage" section in  config.ini. That being said, i haven't added the logic to loop through the section like I did the rest of the code. I think there's also the problem that in some places, functions.php has the path and volume explicitly defined. There's some work to do for mapping storage devices. Also, it only supports showing spaces that are directly connected to the server. I haven't tried mounted drives (you know, like under /mount or whatever) so I don't know if a network share can be displayed or not.
